[package]
name = "booking-manager"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
env_logger = "0.11.8"
libsql = "0.9.18"
log = "0.4.27"
pollster = "0.4.0"
